var page_FALCON_Modules =
[
    [ "Module CommandLineInterface", "page_module_CommandLineInterface.html", null ],
    [ "Module 00CORE", "page_module_00CORE.html", null ],
    [ "Module COREMOD_memory", "page_module_COREMOD_memory.html", null ],
    [ "Module COREMOD_iofits", "page_module_COREMOD_iofits.html", null ],
    [ "Module COREMOD_tools", "page_module_COREMOD_tools.html", null ],
    [ "Module COREMOD_arith", "page_module_COREMOD_arith.html", null ],
    [ "Module ImageStreamIO", "page_module_ImageStreamIO.html", null ],
    [ "Module fft", "page_module_fft.html", null ],
    [ "Module statistic", "page_module_statistic.html", null ],
    [ "Module WFpropagate", "page_module_WFpropagate.html", null ],
    [ "Module psf", "page_module_psf.html", null ],
    [ "Module info", "page_module_info.html", null ],
    [ "Module kdtree", "page_module_kdtree.html", null ],
    [ "Module linARfilterPred", "page_module_linARfilterPred.html", null ],
    [ "Module cudacomp", "page_module_cudacomp.html", null ],
    [ "Module image_filter", "page_module_image_filter.html", null ],
    [ "Module image_basic", "page_module_image_basic.html", null ],
    [ "Module image_format", "page_module_image_format.html", null ],
    [ "Module image_gen", "page_module_image_gen.html", null ],
    [ "Module img_reduce", "page_module_img_reduce.html", null ],
    [ "Module linopt_imtools", "page_module_linopt_imtools.html", null ],
    [ "Module OpticsMaterials", "page_module_OpticsMaterials.html", null ],
    [ "Module OptSystProp", "page_module_OptSystProp.html", null ],
    [ "Module AOsystSim", "page_module_AOsystSim.html", null ],
    [ "Module ZernikePolyn", "page_module_ZernikePolyn.html", null ],
    [ "Module PIAACMCsimul", "page_module_PIAACMCsimul.html", null ]
];